### ISSUE TITLE
Minor issue

### ISSUE THREAD

**Issue by AgentG010** [ShahIndustries/FRCRobot#1]
Very nicely completed so far :) One minor issue though, you should probably initialize your talons inside Drive.cpp, and use RobotMap.h to store the values of their ports. Also, for next meeting, you should have the straight driving code implemented, so create a PID Class and add a Gyro sensor to your Subsystem :)

**Comment by TheTrueMaster** [comment]
Wait so were we supposed to finish the Gyro stuff before  Sat or during Sat?

**Comment by AgentG010** [comment]
The gyro stuff only has to be done before the next meeting, you have 1.5 weeks :)

**Comment by TheTrueMaster** [comment]
Ok
